// Code generated by go-validator; DO NOT EDIT.
// Package config contains models and autogenerated validation code
package config

// Validate validates struct accordingly to fields tags
func (c Config) Validate() []string {
	var errs []string
	if c.BaseUrl == "" {
		errs = append(errs, "BaseUrl is required")
	}
	if c.User == "" {
		errs = append(errs, "User is required")
	}
	if c.Token == "" {
		errs = append(errs, "Token is required")
	}
	if c.MyAccountTag == "" {
		errs = append(errs, "MyAccountTag is required")
	}
	for _, v := range c.Reviewers {
		if e := v.Validate(); len(e) > 0 {
			errs = append(errs, e...)
		}
	}
	if c.DiscordWebHook == "" {
		errs = append(errs, "DiscordWebHook is required")
	}

	return errs
}

// Validate validates struct accordingly to fields tags
func (a Assignee) Validate() []string {
	var errs []string
	if a.ID == "" {
		errs = append(errs, "ID is required")
	}
	if a.Tag == "" {
		errs = append(errs, "Tag is required")
	}
	if a.Name == "" {
		errs = append(errs, "Name is required")
	}
	if a.DiscordID == "" {
		errs = append(errs, "DiscordID is required")
	}

	return errs
}
